variables:
  PROJECT_NAME: "Sintek.Schedule"
before_script:
  - chcp 65001
  - echo "starting build for %PROJECT_NAME%"
  - echo "Restoring NuGet Packages..."
  - '%GitlabRunner%\nuget restore "%PROJECT_NAME%.sln"'
stages:
  - build
  - test
  - test_report
  - deploy
build:
  stage: build
  script:
  - echo "Release build..."
  - '%GitlabRunner%\build %PROJECT_NAME%'
  artifacts:
    untracked: true
stylecop:
  stage: test
  script:
  - echo "starting stylecop"
  - '%GitlabRunner%\ReportStyleCop\runStylecop'
  artifacts:
    paths:
    - StyleCop
pages:
  stage: deploy
  script:
  - '%GitlabRunner%\pages'
  when: always
  dependencies:
  - stylecop
  artifacts:
    paths:
    - public
package:
  stage: deploy
  script:
  - echo "Publishing NuGet package"
  - '%GitlabRunner%\nuget_publish_remote "%CI_BUILD_TAG%" %PROJECT_NAME%'
  only:
  - tags
  dependencies:
  - build
  artifacts:
    paths:
    - "*.nupkg"