variables:
  PROJECT_NAME: "Sintek.Schedule"
before_script:
  - chcp 65001
  - echo "Restoring NuGet Packages..."
  - '%GitlabRunner%\nuget restore "%PROJECT_NAME%.sln"'
stages:
  - build
  - test
  - test_report
  - deploy
build:
  stage: build
  script:
  - echo "Release build..."
  - '%GitlabRunner%\bin\build %PROJECT_NAME%'
  artifacts:
    expire_in: 1 day
    untracked: true
stylecop:
  stage: test
  script:
  - echo "Starting stylecop"
  - '%GitlabRunner%\bin\stylecop'
  artifacts:
    expire_in: 1 day
    paths:
    - StyleCop
metrics:
  stage: test
  script:
  - echo "Starting metrics"
  - '%GitlabRunner%\bin\metrics'
  dependencies:
  - build
  artifacts:
    expire_in: 1 day
    paths:
    - MetricsResults.html
pages:
  stage: deploy
  script:
  - '%GitlabRunner%\bin\pages'
  when: always
  dependencies:
  - stylecop
  - metrics
  artifacts:
    expire_in: 1 mos
    paths:
    - public
package:
  stage: deploy
  script:
  - echo "Publishing NuGet package"
  - '%GitlabRunner%\bin\nuget_publish_remote'
  only:
  - tags
  dependencies:
  - build
  artifacts:
    paths:
    - "*.nupkg"